Organizations:
  - &Shipper
      Name: ShipperMSP
      ID: ShipperMSP
      MSPDir: ../organizations/peerOrganizations/shipper.example.com/msp
      Policies:
        Readers:
          Type: Signature
          Rule: "OR('ShipperMSP.member')"
        Writers:
          Type: Signature
          Rule: "OR('ShipperMSP.member')"
        Admins:
          Type: Signature
          Rule: "OR('ShipperMSP.admin')"
        Endorsement:
          Type: Signature
          Rule: "OR('ShipperMSP.peer')"
      AnchorPeers:
        - Host: peer0.shipper.example.com
          Port: 7051

  - &Freight
      Name: FreightMSP
      ID: FreightMSP
      MSPDir: ../organizations/peerOrganizations/freight.example.com/msp
      Policies:
        Readers:
          Type: Signature
          Rule: "OR('FreightMSP.member')"
        Writers:
          Type: Signature
          Rule: "OR('FreightMSP.member')"
        Admins:
          Type: Signature
          Rule: "OR('FreightMSP.admin')"
        Endorsement:
          Type: Signature
          Rule: "OR('FreightMSP.peer')"
      AnchorPeers:
        - Host: peer0.freight.example.com
          Port: 9051

  - &Carrier
      Name: CarrierMSP
      ID: CarrierMSP
      MSPDir: ../organizations/peerOrganizations/carrier.example.com/msp
      Policies:
        Readers:
          Type: Signature
          Rule: "OR('CarrierMSP.member')"
        Writers:
          Type: Signature
          Rule: "OR('CarrierMSP.member')"
        Admins:
          Type: Signature
          Rule: "OR('CarrierMSP.admin')"
        Endorsement:
          Type: Signature
          Rule: "OR('CarrierMSP.peer')"
      AnchorPeers:
        - Host: peer0.carrier.example.com
          Port: 11051

  - &Custom
      Name: CustomMSP
      ID: CustomMSP
      MSPDir: ../organizations/peerOrganizations/custom.example.com/msp
      Policies:
        Readers:
          Type: Signature
          Rule: "OR('CustomMSP.member')"
        Writers:
          Type: Signature
          Rule: "OR('CustomMSP.member')"
        Admins:
          Type: Signature
          Rule: "OR('CustomMSP.admin')"
        Endorsement:
          Type: Signature
          Rule: "OR('CustomMSP.peer')"
      AnchorPeers:
        - Host: peer0.custom.example.com
          Port: 13051

  - &Consignee
      Name: ConsigneeMSP
      ID: ConsigneeMSP
      MSPDir: ../organizations/peerOrganizations/consignee.example.com/msp
      Policies:
        Readers:
          Type: Signature
          Rule: "OR('ConsigneeMSP.member')"
        Writers:
          Type: Signature
          Rule: "OR('ConsigneeMSP.member')"
        Admins:
          Type: Signature
          Rule: "OR('ConsigneeMSP.admin')"
        Endorsement:
          Type: Signature
          Rule: "OR('ConsigneeMSP.peer')"
      AnchorPeers:
        - Host: peer0.consignee.example.com
          Port: 15051

Capabilities:
  Channel: &ChannelCapabilities
    V2_0: true
  Orderer: &OrdererCapabilities
    V2_0: true
  Application: &ApplicationCapabilities
    V2_0: true

Application: &ApplicationDefaults
  Organizations:

  Policies:
    Readers:
      Type: ImplicitMeta
      Rule: "ANY Readers"
    Writers:
      Type: ImplicitMeta
      Rule: "ANY Writers"
    Admins:
      Type: ImplicitMeta
      Rule: "MAJORITY Admins"
    LifecycleEndorsement:
      Type: ImplicitMeta
      Rule: "MAJORITY Endorsement"
    Endorsement:
      Type: ImplicitMeta
      Rule: "MAJORITY Endorsement"
  Capabilities:
    <<: *ApplicationCapabilities

Orderer: &OrdererDefaults
  OrdererType: etcdraft
  Addresses:
    - orderer0.freight.example.com:9050
    - orderer1.carrier.example.com:11050
    - orderer2.custom.example.com:13050
  EtcdRaft:
    Consenters:
    - Host: orderer0.freight.example.com
      Port: 9050
      ClientTLSCert: ../organizations/peerOrganizations/freight.example.com/orderers/orderer0.freight.example.com/tls/server.crt
      ServerTLSCert: ../organizations/peerOrganizations/freight.example.com/orderers/orderer0.freight.example.com/tls/server.crt
    - Host: orderer1.carrier.example.com
      Port: 11050
      ClientTLSCert: ../organizations/peerOrganizations/carrier.example.com/orderers/orderer1.carrier.example.com/tls/server.crt
      ServerTLSCert: ../organizations/peerOrganizations/carrier.example.com/orderers/orderer1.carrier.example.com/tls/server.crt
    - Host: orderer2.custom.example.com
      Port: 13050
      ClientTLSCert: ../organizations/peerOrganizations/custom.example.com/orderers/orderer2.custom.example.com/tls/server.crt
      ServerTLSCert: ../organizations/peerOrganizations/custom.example.com/orderers/orderer2.custom.example.com/tls/server.crt
  BatchTimeout: 2s
  BatchSize:
    MaxMessageCount: 10
    AbsoluteMaxBytes: 99 MB
    PreferredMaxBytes: 512 KB
  Organizations:
  Policies:
    Readers:
      Type: ImplicitMeta
      Rule: "ANY Readers"
    Writers:
      Type: ImplicitMeta
      Rule: "ANY Writers"
    Admins:
      Type: ImplicitMeta
      Rule: "MAJORITY Admins"
    BlockValidation:
      Type: ImplicitMeta
      Rule: "ANY Writers"

Channel: &ChannelDefaults
  Policies:
    Readers:
      Type: ImplicitMeta
      Rule: "ANY Readers"
    Writers:
      Type: ImplicitMeta
      Rule: "ANY Writers"
    Admins:
      Type: ImplicitMeta
      Rule: "MAJORITY Admins"
  Capabilities:
    <<: *ChannelCapabilities

Profiles:
  OrdererSystemGenesisChannel:
    <<: *ChannelDefaults
    Capabilities:
      <<: *ChannelCapabilities
    Orderer:
      <<: *OrdererDefaults
      Organizations:
        - *Freight
        - *Carrier
        - *Custom
      Capabilities:
        <<: *OrdererCapabilities
    Consortiums:
      SupplychainConsortium:
        Organizations:
          - *Shipper
          - *Freight
          - *Carrier
          - *Custom
          - *Consignee
  
  ApplicationChannel:
    Consortium: SupplychainConsortium
    <<: *ChannelDefaults
    Application:
      <<: *ApplicationDefaults
      Organizations:
        - *Shipper
        - *Freight
        - *Carrier
        - *Custom
        - *Consignee
      Capabilities:
        <<: *ApplicationCapabilities